name: fast_immutable_equatable
description: A simple Dart package that provides immutable equatable's with the option to store the hashes.
version: 1.0.0
repository: https://github.com/bvoq/fast_immutable_equatable

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  fast_immutable_collections: ^9.1.6
  lint: ^2.1.2
  test: ^1.16.0

dependencies:
  collection: ^1.15.0
  meta: ^1.8.0
